// Utility functions for common button actions across the platform

export const downloadFile = (filename: string, content: string, type: string = 'text/plain') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadPDF = (title: string, content: string) => {
  // Simulate PDF download with HTML content
  const pdfContent = `
<!DOCTYPE html>
<html>
<head>
    <title>${title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        p { margin-bottom: 15px; }
        .header { text-align: center; margin-bottom: 40px; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${title}</h1>
        <p>Generated by GovRise Australian Immigration Platform</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
    </div>
    ${content}
    <div class="footer">
        <p>© 2025 GovRise. All rights reserved.</p>
        <p>For the latest information, visit our platform at govrise.org</p>
    </div>
</body>
</html>`;
  
  downloadFile(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`, pdfContent, 'text/html');
};

export const shareContent = (title: string, url?: string) => {
  const shareData = {
    title: title,
    text: `Check out this resource: ${title}`,
    url: url || window.location.href
  };

  if (navigator.share) {
    navigator.share(shareData).catch(console.error);
  } else {
    // Fallback: copy to clipboard
    const shareText = `${shareData.title}\n${shareData.text}\n${shareData.url}`;
    navigator.clipboard.writeText(shareText).then(() => {
      showNotification('Link copied to clipboard!', 'success');
    }).catch(() => {
      // Final fallback: show share modal
      showShareModal(shareData);
    });
  }
};

export const exportData = (data: any, filename: string, format: 'json' | 'csv' | 'xlsx' = 'json') => {
  let content: string;
  let mimeType: string;
  let fileExtension: string;

  switch (format) {
    case 'csv':
      content = convertToCSV(data);
      mimeType = 'text/csv';
      fileExtension = 'csv';
      break;
    case 'xlsx':
      // For Excel format, we'll use CSV as a fallback
      content = convertToCSV(data);
      mimeType = 'application/vnd.ms-excel';
      fileExtension = 'csv';
      break;
    default:
      content = JSON.stringify(data, null, 2);
      mimeType = 'application/json';
      fileExtension = 'json';
  }

  downloadFile(`${filename}.${fileExtension}`, content, mimeType);
};

export const printContent = (title: string, content: string) => {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
          <title>${title}</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
              h1 { color: #1e40af; }
              h2 { color: #374151; margin-top: 25px; }
              @media print {
                  body { margin: 0; }
                  .no-print { display: none; }
              }
          </style>
      </head>
      <body>
          <h1>${title}</h1>
          ${content}
          <script>
              window.onload = function() {
                  window.print();
                  window.onafterprint = function() {
                      window.close();
                  };
              };
          </script>
      </body>
      </html>
    `);
    printWindow.document.close();
  }
};

export const saveBookmark = (title: string, url?: string) => {
  const bookmarks = JSON.parse(localStorage.getItem('govrise-bookmarks') || '[]');
  const bookmark = {
    id: Date.now().toString(),
    title,
    url: url || window.location.href,
    savedAt: new Date().toISOString()
  };
  
  // Check if already bookmarked
  const exists = bookmarks.find((b: any) => b.url === bookmark.url);
  if (!exists) {
    bookmarks.push(bookmark);
    localStorage.setItem('govrise-bookmarks', JSON.stringify(bookmarks));
    showNotification('Bookmark saved!', 'success');
  } else {
    showNotification('Already bookmarked!', 'info');
  }
};

// Helper functions
const convertToCSV = (data: any[]): string => {
  if (!Array.isArray(data) || data.length === 0) {
    return '';
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header];
        // Escape quotes and wrap in quotes if contains comma or quote
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value;
      }).join(',')
    )
  ].join('\n');

  return csvContent;
};

const showShareModal = (shareData: any) => {
  // Create a simple modal for sharing
  const modal = document.createElement('div');
  modal.className = 'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50';
  modal.innerHTML = `
    <div class="bg-white rounded-lg p-6 max-w-md w-full mx-4">
      <h3 class="text-lg font-semibold mb-4">Share this content</h3>
      <div class="space-y-3">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Title</label>
          <input type="text" value="${shareData.title}" readonly class="w-full p-2 border rounded-md bg-gray-50">
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">URL</label>
          <div class="flex">
            <input type="text" value="${shareData.url}" readonly class="flex-1 p-2 border rounded-l-md bg-gray-50" id="shareUrl">
            <button onclick="navigator.clipboard.writeText('${shareData.url}').then(() => alert('Copied!'))" class="px-4 py-2 bg-blue-600 text-white rounded-r-md hover:bg-blue-700">Copy</button>
          </div>
        </div>
      </div>
      <div class="flex justify-end mt-6">
        <button onclick="this.closest('.fixed').remove()" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">Close</button>
      </div>
    </div>
  `;
  
  document.body.appendChild(modal);
  
  // Remove modal when clicking outside
  modal.addEventListener('click', (e) => {
    if (e.target === modal) {
      modal.remove();
    }
  });
};

const showNotification = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
  const notification = document.createElement('div');
  notification.className = `fixed top-4 right-4 p-4 rounded-lg text-white z-50 ${
    type === 'success' ? 'bg-green-500' : 
    type === 'error' ? 'bg-red-500' : 
    'bg-blue-500'
  }`;
  notification.textContent = message;
  
  document.body.appendChild(notification);
  
  // Animate in
  notification.style.transform = 'translateX(100%)';
  notification.style.transition = 'transform 0.3s ease';
  setTimeout(() => {
    notification.style.transform = 'translateX(0)';
  }, 10);
  
  // Remove after 3 seconds
  setTimeout(() => {
    notification.style.transform = 'translateX(100%)';
    setTimeout(() => {
      notification.remove();
    }, 300);
  }, 3000);
};